### ISSUE TITLE
Use custom spark libraries

### ISSUE THREAD

**Issue by gauravkumar37** [ibm-et/spark-kernel#104]
Hi,

I noticed that spark-kernel uses its own dependencies for spark.
Would it be possible to use the environment's / own distribution of spark. For instance, I am using spark distributed by CDH, how would I go about using those libraries instead?

Thanks.

**Comment by rcsenkbeil** [comment]
The Spark Kernel uses standard Spark libraries (like Spark core) to provide the facilities needed to connect to a Spark cluster.

If you're talking about using a version other than 1.2.1, then you will need to wait until the kernel is built with the new version _or_ you can try building it yourself and changing the version [here](https://github.com/ibm-et/spark-kernel/blob/master/project/Common.scala#L40).

If you actually want to bring in your own custom version of the Spark library, I think you could try to build the kernel with the [Spark dependencies](https://github.com/ibm-et/spark-kernel/blob/master/kernel-api/build.sbt#L49) marked as provided and then add the Spark library jars to the classpath of the kernel at startup using something like:

 `java -classpath '.:/path/to/spark/libraries/*' com.ibm.spark.SparkKernel`

If your libraries were a different version than 1.2.1, you would need to also see if the kernel could be built against that version (even if marked provided).

**Comment by lbustelo** [comment]
@gauravkumar37 Look at PR #196. Would that solve your issues?

**Comment by lbustelo** [comment]
closed fixed by #196
