### ISSUE TITLE
How to reset session with client command?

### ISSUE THREAD

**Issue by Gwill** [ibm-et/spark-kernel#106]
How to reset session with client command?

**Comment by rcsenkbeil** [comment]
Do you mean that you want to reset the interpreter from the client library? Or restart the kernel from the client library? Or something else?

**Comment by Gwill** [comment]
restart the kernel from the client library.

**Comment by rcsenkbeil** [comment]
There is currently no client-side command to restart the entire kernel. There was an intention to provide a shutdown command based on the [shutdown request](https://github.com/ibm-et/spark-kernel/blob/master/protocol/src/main/scala/com/ibm/spark/kernel/protocol/v5/content/ShutdownRequest.scala); however, nothing has been implemented as of yet.
