### ISSUE TITLE
How to make IPython Notebook aware of the scala syntax when using Spark Kernel?

### ISSUE THREAD

**Issue by zer0n** [ibm-et/spark-kernel#109]
Not really an issue of Spark Kernel but I guess that you guys would know best.

**Comment by rcsenkbeil** [comment]
The language setting is supposed to provide the highlighting using a Javascript file with the same name, but we've found that Scala falls under the "clike.js" file (for the C family languages). The solution was to use a custom profile to provide custom.js that loaded the correct Javascript file and used it for syntax highlighting.

I haven't checked recently to see if that is still a problem.

**Comment by tribbloid** [comment]
thanks a lot, I've encounter this problem in IPy 3.1 and I thought this is a kernel_info_reply issue in messaging. Could you tell us how you override this js file to enable syntax highlighting and comment shortcut?
