### ISSUE TITLE
IPython notebook connection problem

### ISSUE THREAD

**Issue by mettinger** [ibm-et/spark-kernel#110]
When I open a new Spark notebook there seems to be a connection problem as I cannot run a command and the notebook just hangs.  I noticed a warning messages in the notebook server:

[W 11:44:17.980 NotebookApp] Timeout waiting for kernel_info reply from b10b7bb1-7728-4143-883c-1b625eb01f2a

Any advice much appreciated!

(Below is the full server output from start:)

Marks-MacBook-Pro:python-mettinger mettinger$ ipython notebook
[I 11:43:44.076 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
[I 11:43:44.093 NotebookApp] Serving notebooks from local directory: /Users/mettinger/GitHub/python-mettinger
[I 11:43:44.093 NotebookApp] 0 active kernels
[I 11:43:44.093 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 11:43:44.093 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 11:43:52.227 NotebookApp] Notebook scratch.ipynb is not trusted
[I 11:43:52.738 NotebookApp] Kernel started: 2bd80d1c-5986-4cd4-b269-66c096c52ba8
[I 11:44:07.516 NotebookApp] Creating new notebook in
[I 11:44:07.961 NotebookApp] Kernel started: b10b7bb1-7728-4143-883c-1b625eb01f2a
15/05/20 11:44:08 [INFO] c.i.s.SparkKernel$$anon$1 - Kernel version: 0.1.2-SNAPSHOT
15/05/20 11:44:08 [INFO] c.i.s.SparkKernel$$anon$1 - Scala version: 2.10.4
15/05/20 11:44:08 [INFO] c.i.s.SparkKernel$$anon$1 - Initializing internal actor system
15/05/20 11:44:09 [INFO] c.i.s.SparkKernel$$anon$1 - Connection Profile: {
  "stdin_port" : 50593,
  "control_port" : 50594,
  "hb_port" : 50595,
  "shell_port" : 50591,
  "iopub_port" : 50592,
  "ip" : "127.0.0.1",
  "transport" : "tcp",
  "signature_scheme" : "hmac-sha256",
  "key" : "ec6f64b1-4141-42d9-bacc-dc5f2bb545aa"
}
15/05/20 11:44:09 [INFO] c.i.s.SparkKernel$$anon$1 - Constructing interpreter with 4 threads and with arguments:
15/05/20 11:44:09 [WARN] o.a.h.u.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/05/20 11:44:09 [INFO] o.s.j.s.Server - jetty-8.y.z-SNAPSHOT
15/05/20 11:44:09 [INFO] o.s.j.s.AbstractConnector - Started SocketConnector@0.0.0.0:50939
15/05/20 11:44:11 [INFO] c.i.s.SparkKernel$$anon$1 - Using local[*] as Spark Master
15/05/20 11:44:11 [INFO] c.i.s.SparkKernel$$anon$1 - Using IBM Spark Kernel as Spark application name
15/05/20 11:44:11 [WARN] c.i.s.SparkKernel$$anon$1 - Locked to Scala interpreter with SparkIMain until decoupled!
15/05/20 11:44:11 [WARN] c.i.s.SparkKernel$$anon$1 - Unable to control initialization of REPL class server!
15/05/20 11:44:11 [INFO] c.i.s.SparkKernel$$anon$1 - REPL Class Server Uri: http://192.168.254.176:50939
15/05/20 11:44:12 [INFO] Remoting - Starting remoting
15/05/20 11:44:12 [INFO] Remoting - Remoting started; listening on addresses :[akka.tcp://sparkDriver@192.168.254.176:51133]
15/05/20 11:44:12 [INFO] o.s.j.s.Server - jetty-8.y.z-SNAPSHOT
15/05/20 11:44:12 [INFO] o.s.j.s.AbstractConnector - Started SocketConnector@0.0.0.0:51135
15/05/20 11:44:12 [INFO] o.s.j.s.Server - jetty-8.y.z-SNAPSHOT
15/05/20 11:44:12 [INFO] o.s.j.s.AbstractConnector - Started SelectChannelConnector@0.0.0.0:4040
15/05/20 11:44:14 [INFO] c.i.s.SparkKernel$$anon$1 - Running in local mode! Not adding self as dependency!
15/05/20 11:44:14 [WARN] c.i.s.SparkKernel$$anon$1 - No external magics provided to MagicLoader!
15/05/20 11:44:14 [INFO] c.i.s.SparkKernel$$anon$1 - Marking relay as ready for receiving messages
15/05/20 11:44:14 [INFO] c.i.s.k.p.v.r.KernelMessageRelay - Unstashing all messages received!
15/05/20 11:44:14 [INFO] c.i.s.k.p.v.r.KernelMessageRelay - Relay is now fully ready to receive messages!
[W 11:44:17.980 NotebookApp] Timeout waiting for kernel_info reply from b10b7bb1-7728-4143-883c-1b625eb01f2a

**Comment by rcsenkbeil** [comment]
I have seen the timeout notification and have been able to run the notebook with the kernel. Do you know what version of ZeroMQ the kernel is using? I've added a log of the ZeroMQ version to the Spark Kernel (this is something that is commonly requested). If it is greater than 2.2.0, the Spark Kernel will not response to ZeroMQ messages due to the nature of the current ZeroMQ library dependency.

**Comment by rcsenkbeil** [comment]
FYI, you might want to try the latest commit of the kernel. We recently switched to JeroMQ, which might help with connection problems.

**Comment by zhuge19881117** [comment]
any solution here? i got a similar issue. I could use the bin/sparkkernel --master spark://uri:7071 to connect the kernel with spark cluster. but the ipython notebook would give me a timeout and then create a kernel connecting to local[*].  I checkout the master branch and compile with spark 1.4.0.
Any one could help?
Log like this:
[I 14:55:40.076 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
[I 14:55:40.121 NotebookApp] Serving notebooks from local directory: /home/dpdcadmin
[I 14:55:40.121 NotebookApp] 0 active kernels 
[I 14:55:40.122 NotebookApp] The IPython Notebook is running at: http://192.168.128.20:8888/
[I 14:55:40.122 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 14:55:40.123 NotebookApp] No web browser found: could not locate runnable browser.
[I 14:55:50.700 NotebookApp] Kernel started: 62287d6e-a83c-435e-8dea-b80796590ba0
15/08/06 14:55:52 [INFO] c.i.s.SparkKernel$$anon$1 - Kernel version: 0.1.2-SNAPSHOT
15/08/06 14:55:52 [INFO] c.i.s.SparkKernel$$anon$1 - Scala version: 2.10.4
15/08/06 14:55:52 [INFO] c.i.s.SparkKernel$$anon$1 - ZeroMQ (JeroMQ) version: 3.2.2
15/08/06 14:55:52 [INFO] c.i.s.SparkKernel$$anon$1 - Initializing internal actor system
15/08/06 14:55:52 [INFO] c.i.s.SparkKernel$$anon$1 - Connection Profile: {
  "stdin_port" : 48341,
  "control_port" : 55484,
  "hb_port" : 44731,
  "shell_port" : 55219,
  "iopub_port" : 48464,
  "ip" : "127.0.0.1",
  "transport" : "tcp",
  "signature_scheme" : "hmac-sha256",
  "key" : "04b28efa-3e5c-41a9-9e1d-707b89b5b363"
}
15/08/06 14:55:52 [INFO] c.i.s.SparkKernel$$anon$1 - Constructing interpreter with 4 threads and with arguments: 
15/08/06 14:55:52 [INFO] c.i.s.k.p.v.r.KernelMessageRelay - Not ready for messages! Stashing until ready!
15/08/06 14:55:53 [WARN] o.a.h.u.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/08/06 14:55:53 [INFO] o.s.j.s.Server - jetty-8.y.z-SNAPSHOT
15/08/06 14:55:53 [INFO] o.s.j.s.AbstractConnector - Started SocketConnector@0.0.0.0:32777
15/08/06 14:55:57 [INFO] c.i.s.SparkKernel$$anon$1 - Using local[*] as Spark Master
15/08/06 14:55:57 [INFO] c.i.s.SparkKernel$$anon$1 - Using IBM Spark Kernel as Spark application name
15/08/06 14:55:57 [WARN] c.i.s.SparkKernel$$anon$1 - Locked to Scala interpreter with SparkIMain until decoupled!
15/08/06 14:55:57 [WARN] c.i.s.SparkKernel$$anon$1 - Unable to control initialization of REPL class server!
15/08/06 14:55:57 [INFO] c.i.s.SparkKernel$$anon$1 - REPL Class Server Uri: http://192.168.128.20:32777
15/08/06 14:55:57 [INFO] Remoting - Starting remoting
15/08/06 14:55:57 [INFO] Remoting - Remoting started; listening on addresses :[akka.tcp://sparkDriver@192.168.128.20:42735]
15/08/06 14:55:57 [INFO] o.s.j.s.Server - jetty-8.y.z-SNAPSHOT
15/08/06 14:55:57 [INFO] o.s.j.s.AbstractConnector - Started SocketConnector@0.0.0.0:59166
15/08/06 14:55:57 [INFO] o.s.j.s.Server - jetty-8.y.z-SNAPSHOT
15/08/06 14:55:57 [INFO] o.s.j.s.AbstractConnector - Started SelectChannelConnector@0.0.0.0:4040
15/08/06 14:55:58 [WARN] c.i.s.k.p.v.s.KernelOutputStream - Suppressing empty output: ''
[W 14:56:00.718 NotebookApp] Timeout waiting for kernel_info reply from 62287d6e-a83c-435e-8dea-b80796590ba0
15/08/06 14:56:00 [INFO] c.i.s.k.p.v.r.KernelMessageRelay - Not ready for messages! Stashing until ready!
15/08/06 14:56:01 [INFO] c.i.s.SparkKernel$$anon$1 - Running in local mode! Not adding self as dependency!
15/08/06 14:56:02 [WARN] c.i.s.SparkKernel$$anon$1 - No external magics provided to MagicLoader!
15/08/06 14:56:02 [INFO] c.i.s.SparkKernel$$anon$1 - Marking relay as ready for receiving messages
15/08/06 14:56:02 [INFO] c.i.s.k.p.v.r.KernelMessageRelay - Unstashing all messages received!
15/08/06 14:56:02 [INFO] c.i.s.k.p.v.r.KernelMessageRelay - Relay is now fully ready to receive messages!

**Comment by sunnykumar09** [comment]
@zhuge19881117 do you have your spark running through yarn on the cluster.
Because we have face a similar issue (CDH cluster with yarn) and there is an issue already open for that.

**Comment by zhuge19881117** [comment]
@sunnykumar09  it is a standalone cluster and it is a apache version of spark.

**Comment by lbustelo** [comment]
We are not able to reproduce this issue. If you are still experiencing problems, open another issue or contact us through gitter.
