### ISSUE TITLE
Problems running a spark.streaming example within an IPython Notebook

### ISSUE THREAD

**Issue by mkrudele** [ibm-et/spark-kernel#111]
I have created a very basic notebook to test spark streaming api. When I run it nothing happens, the node runs indefinitely. The same example works using the spark submit command line. Any idea of what I missed? Any option that should be set in the spark kernel json config file?
This is what I'm trying to do:

import org.apache.spark._
import org.apache.spark.storage.StorageLevel
import org.apache.spark.streaming._
import org.apache.spark.streaming.receiver.Receiver
import org.apache.spark.streaming.StreamingContext._
import scala.io.Source

// Create a eceiver on a file for test purposes
//
class FileReceiver(fileUrl: String) extends Receiver\[String\](StorageLevel.MEMORY_AND_DISK_2) {

  def onStart() {
    new Thread("File Receiver") {
      override def run() { receive() }
    }.start()
  }

  def onStop() {
  }

  /** Send fake data */
  private def receive() {
    val l = List("this is a list of lines", "to return to the caller", "even if that is nonsense",
                       "don't worry  about,", "just type something", "nel mezzo del cammin di nostra vita",
                       "mi ritrovai per una selva oscura", "che la diritta via era smarrita")
    for(line <- l) {
      store(line)
    }
  }
}

// Create a local StreamingContext with batch duration of 1 minute.
//
val ssc = new StreamingContext(sc, Seconds(1))

val lines = ssc.receiverStream(new FileReceiver(aFile))

// Split each line into words
//
val words = lines.flatMap(_.split(" "))

// Count each word in each batch
//
val pairs = words.map(w => (w, 1))
val wordCounts = pairs.reduceByKey(_ + _)

// Print the first ten elements of each RDD generated in this DStream to the console
wordCounts.print()

ssc.start()
ssc.awaitTermination()
println("everything done!")

**Comment by rcsenkbeil** [comment]
Unfortunately, the magic we employ to capture standard out/standard error does not work with threads created by Apache Spark. The `wordCounts.print()` that you are performing does a `take(10)` from inside the `wordCounts.foreachRDD(...)` method, which executes the function inside a Spark-created thread.

To get around this, you can use `foreachRDD` combined with `kernel.out.println` to do the same thing.

Here is your notebook with the updated code: http://nbviewer.ipython.org/gist/anonymous/3a24d0c9ca574359baaa

Keep in mind that multiple outputs in different threads are all redirected to the most recently executed IPython cell.

**Comment by mkrudele** [comment]
Awesome! Works, thanks.
