### ISSUE TITLE
could not open static file

### ISSUE THREAD

**Issue by pratikjd** [ibm-et/spark-kernel#115]
i am running spark-kernel on virtualbox . when i start ipython notebook i get the error "could not open static file "

![static](https://cloud.githubusercontent.com/assets/13032246/8329777/d3e86c00-1a99-11e5-8925-eb21abd23427.png)

**Comment by rcsenkbeil** [comment]
Is this using our provided Vagrant setup or your own? If it involved cloning out IPython, you need to make sure it was recursively done such that the static html components submodule was also cloned.

**Comment by lbustelo** [comment]
Closing due to no reply. @pratikjd If you are still having problems, open a new issue.
