### ISSUE TITLE
Documentation for REST server

### ISSUE THREAD

**Issue by phatak-dev** [ibm-et/spark-kernel#116]
Recent spark-kernel talk at Spark meetup mentions support for REST interface to the kernel. But I can't find any documentation to the same. Can someone point how to use REST part of the kernel?

**Comment by rcsenkbeil** [comment]
Hi. The Spark meetup talk was presenting prototypes on top of the Spark Kernel. The RESTful interface is not part of the Spark Kernel itself (although that isn't to say that it would be difficult to add).

The RESTful interface was very few lines of code as we used [Scala Play](https://playframework.com) to provide the RESTful endpoints and the [client library](https://github.com/ibm-et/spark-kernel/wiki/Guide-for-the-Spark-Kernel-Client) to communicate the request and get the response back.

It looked similar to this:

```scala
def variable(name: String) = Action.async(parse.json) { implicit request =>
  val transformation = name + /* Do something to parse and build transformed RDD based on request such as limit == take(#) */

  val code = s"kernel.stream.sendAll(com.ibm.spark.utils.json.RddToJson.convert(${transformation}))"

  // Create a promise to allow our RESTful response to be asynchronous
  val resultPromise = promise[Result]

  // Execute the code (might look like "kernel.stream.sendall(RddToJson.convert(myRdd.take(10)))")
  client.execute(code).onStream(streamContent => {
    // On getting the result, send it back
    promise.success(Ok(streamContent.text))
  })

  // Return the future containing the result
  resultPromise.future
}
```

**Comment by rcsenkbeil** [comment]
Closing as there are no current plans to add the REST server from the demo to this project.
