### ISSUE TITLE
how do I compile against spark-1.4?

### ISSUE THREAD

**Issue by nalui333** [ibm-et/spark-kernel#117]
Maybe this is a newbie question but what's the best practice to compile against spark version 1.4. Would be a good idea to add the command for sbt compile with various versions of spark etc. Thanks

**Comment by rcsenkbeil** [comment]
For Spark 1.4, you should be able to compile via the following (in bash in the root of the project):

    APACHE_SPARK_VERSION="1.4.0" sbt compile

Same goes for pack:

    APACHE_SPARK_VERSION="1.4.0" sbt pack

Basically, we read an environment variable to indicate the version of Spark to use. If no environment variable is provided, we default to `1.3.1` at the moment.

**Comment by nalui333** [comment]
thanks. appreciate the quick response.
