### ISSUE TITLE
Spark 1.4.1

### ISSUE THREAD

**Issue by maver1ck** [ibm-et/spark-kernel#120]
Hi,
How can I use spark kernel with Spark 1.4.1 ?

**Comment by cjm5325** [comment]
Set APACHE_SPARK_VERSION environment variable to "1.4.1" and recompile should be it?

https://github.com/ibm-et/spark-kernel/blob/b673937de1ab98ddd508a1460e5e493dae902610/project/Common.scala

@rcsenkbeil ?

**Comment by Lull3rSkat3r** [comment]
@cjm5325, yes that is correct. @maver1ck please see issue #117.
