### ISSUE TITLE
Spark kernel cluster mode

### ISSUE THREAD

**Issue by vnkesarwani** [ibm-et/spark-kernel#122]
Hi,

I have few basic questions on spark kernel..
1. Is Spark kernel acts as a spark driver?? that means it works in client mode and should be installed near to cluster??
2. Can spark kernel connect to Yarn or Mesos cluster in spark cluster mode??
3. In spark kernel for every request do we create a new interpreter instance and attaching a already created spark context???

Thanks,
Vinay

**Comment by lbustelo** [comment]
#1: The Spark Kernel is a driver program. It holds the instance if a spark context. With the right jars, it is able to connect to a variety of cluster setups. 

#2: we do not have direct experience with running against Yarn, but we do run the kernel against a mesos cluster mode. 

#3: the relationship is 1:1 spark kernel to spark context. For all intends and purposes, you can say that there is a single interpreter shares among all request, but it is not as simple as that. There is a configurable pool all sharing the same context. 


Gino B.

**Comment by vnkesarwani** [comment]
Hi,

For point #3 i am not very sure if that is the case 1:1 for spark kernel to spark context.

Following is the scenario i have tested..
step1 : started kernel in local mode
step2 : launched 4 ipython notebooks
step3 : executed sc.toString  and it shows different sparkContext IDs.
step4 : executed sc.stop in one of the client ; and then a simple command it failed as spark context was closed
step5: on other client notebook sc.xxxxcode  works fine.

Please let me know more in #3

**Comment by lbustelo** [comment]
Not sure I understand your sequence of steps. All seems ok except step 1. You don't start a kernel yourself, rather the notebook manages the kernels if you've configured correctly. 

So without step one. It is working as I explained. For each new notebook you get a kernel and each kernel has its own context. 

Gino B.

**Comment by lbustelo** [comment]
Closing this one. @vnkesarwani if you have more question, you can create a new issue or get a hold of us on gitter.
