### ISSUE TITLE
Tuples and other things don't print 

### ISSUE THREAD

**Issue by slowenthal** [ibm-et/spark-kernel#124]
In [45]:

println(x)
(Duos For Violin and Cello,1)
In [46]:

x
In [47]:               <======   Didn't print anything

println(x)
(Duos For Violin and Cello,1)

Same thing with a class - we need the println

In [52]:

x.getClass
In [55]:

println(x.getClass)
class scala.Tuple2

**Comment by bpburns** [comment]
This is most likely to do messages being sent out of order.  I've seen execution_result being sent after status idle.  See jupyter/jupyter-js-services#44.

**Comment by wellecks** [comment]
It looks like there's a bug in `ScalaInterpreter.truncateResult`; the regex fails when the value is a tuple, causing an empty output to be returned.

I'll also look into why the `execute_result` arrives after the `status: idle`, and whether it should be changed
