### ISSUE TITLE
if sprkcontext is closed, do we have to restart kernel??

### ISSUE THREAD

**Issue by vnkesarwani** [ibm-et/spark-kernel#127]
Hi,

I have opened 4 clients with one spark kernel and if one of the client calls sc.close(), should other clients get affected?? or any other approach to solve this??

How do you add a user jar developed in java and run different main classes in the jar?? 

Regards,
Vinay

**Comment by Lull3rSkat3r** [comment]
Each kernel runs as an independent process with its own spark context. Calling sc.close on one kernel will not affect another kernel. If you do close the spark context, you can simply execute some code to create another context. Depending on the use case it may be simpler to restart the kernel.

In regards to adding a user jar, you can add a jar using the AddJar magic:
```scala
%AddJar http://example.com/some_lib.jar 
//or
%AddJar file:/path/to/some/lib.jar
```
As shown above, you can give the magic a url or path on the file system of the kernel.

See the AddJars  [documentation](https://github.com/ibm-et/spark-kernel/wiki/List-of-Current-Magics-for-the-Spark-Kernel) for more information.
