### ISSUE TITLE
spark --properties-file command line options

### ISSUE THREAD

**Issue by jerrylam** [ibm-et/spark-kernel#135]
Hi there, I wonder if --properties-file option is allowed? The most difficult part to use spark-kernel is configurations. spark-submit or spark-shell -h will tell you what spark users tend to use and spark-kernel should make those options available as well.

**Comment by nimbusgo** [comment]
+1 for this

Here's the java code in spark which --properties-file invokes: https://github.com/apache/spark/blob/master/launcher/src/main/java/org/apache/spark/launcher/AbstractCommandBuilder.java#L295

**Comment by lbustelo** [comment]
#196 is trying to address this. still WIP

**Comment by lbustelo** [comment]
#196 already supports this... interested in getting someone to take it for a ride and give me a +1

**Comment by lbustelo** [comment]
closed fixed by #196
