### ISSUE TITLE
Invalid comm open target_name sent to kernel causes Jupyter 4.x to abort

### ISSUE THREAD

**Issue by chipsenkbeil** [ibm-et/spark-kernel#141]
Quoting @nimbusgo from gitter:

> so, I'm trying to run the latest jupyter notebook with the spark kernel and it's not going well. I'm getting this when it starts up:
15/09/23 11:26:43 [WARN] c.i.s.k.p.v.k.s.Shell - Parent header is null for message 6A6833F6E7164EFFAA5987572F847340 of type comm_open
15/09/23 11:26:43 [WARN] c.i.s.k.p.v.h.CommOpenHandler - Received invalid target for Comm Open: ipython.widget
Abort trap: 6
and it actually kills the notebook

We currently log the invalid target and then send an immediate comm_close following the [specification](http://ipython.org/ipython-doc/stable/development/messaging.html#opening-a-comm). Current implementation can be found [here](https://github.com/ibm-et/spark-kernel/blob/master/kernel/src/main/scala/com/ibm/spark/kernel/protocol/v5/handler/CommOpenHandler.scala#L66).

> If the target_name key is not found on the receiving side, then it should immediately reply with a comm_close message to avoid an inconsistent state.

**Comment by lbustelo** [comment]
As part of jupyter-incubator/declarativewidgets we are running Jupyter 4 and Spark Kernel and we do not see any problems due to the warning above.

@bpburns is also running on Jupyter 4 and does not see the error.

Closing...
