### ISSUE TITLE
User can set the location to where JARs are downloaded when starting spark-kernel

### ISSUE THREAD

**Issue by dockter-84** [ibm-et/spark-kernel#142]
In the [AddJar](https://github.com/ibm-et/spark-kernel/blob/413c30fba7ad1abb0b328d12bc92a6a76dbef6ba/kernel/src/main/scala/com/ibm/spark/magic/builtin/AddJar.scala#L34) class we see that there is a `TODO:` to figure out a better location to download files.  Can the location be "injected" into the class via an operating system environment variable?

My python chops are better than my scala,  so in python it would look something like this: 

```python
jar_storage_location = os.environ.get('SPARK_KERNEL_LIB', '/usr/local/lib/')
```

The selection of "/usr/local/lib/" as a default is just one possibility based on https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

If this cannot be implemented, are there any other ways we could programmatically alter the location of the library directory?

**Comment by cjm5325** [comment]
Yep, [CommandLine](https://github.com/ibm-et/spark-kernel/blob/b5b0dc1995ab010d0f0570fbb9fe0f4f19817e03/kernel/src/main/scala/com/ibm/spark/boot/CommandLineOptions.scala) too.

**Comment by lbustelo** [comment]
@dockter-84 
We typically run the spark kernel within a docker container, so selecting the directory has not been an issue, it is all encapsulated by the container. Each container instance gets its own /tmp area.

Now, if what you are worried is running multiple kernels directly on the host, then I can see that our selection of `/tmp' for all jars (regardless of kernel instance) could be an issue. Won't changing it to any other single location (i.e. `/usr/local/lib/`) will result in the same issue.

I looks like we need to:
1. Leave it up to the user to start the kernel on different directories. Something that I'm not sure can be configured on Jupyter.
2. Have the kernel create a random temp directory (using `File.createTempFile`) where it stores the jars for that instance.

**Comment by dockter-84** [comment]
Here are the constraints we have:
  1. The system is a "classic" Linux-based machine with multiple userids.
  2. Each userid may run a common or independent version of spark-kernel.
  3. External programs need to know the location of the libraries for each user.

So we would like a way to "inject" the location of the spark-kernel libraries so the users don't over-write each other's libraries and external programs can also use the libraries.  By using some type of injection, an external program can do the collision avoidance.

**Comment by lbustelo** [comment]
@dockter-84 
Got it... thanks for the clarification.

**Comment by lbustelo** [comment]
We will start working on this today... we will implement the following:
- [ ] Add a new config property 'jar_dir' settable from env JAR_DIR
- [ ] If config is set, and directory exists, jars will be downloaded to sed directory
- [ ] If confis is not set, the kernel will create a temp dir and use that

**Comment by lbustelo** [comment]
Pushed branch https://github.com/ibm-et/spark-kernel/tree/Issue142
Still remaining: 
- [ ] fixing AddJarSpec test that refer to JarStorageLocation
- [ ] Add simple tests for com.ibm.spark.magic.builtin.AddJar#getJarDir

**Comment by lbustelo** [comment]
Option is --jar-dir
1. It is optional
2. When set it must be set to an existing directory
3. It is not set or does not exist, we now generate a random temporary directory and use that

It can also be set with env variable JAR_DIR

**Comment by lbustelo** [comment]
Closing this since the PR #152 was merged
