### ISSUE TITLE
Build failure on windows with mingw

### ISSUE THREAD

**Issue by wtcooper** [ibm-et/spark-kernel#147]
I'm able to build successfully (sbt compile, sbt pack) in mingw/msys, but when I try to launch with the bin/sparkkernel script if fails:

Error: Could not find or load main class com.ibm.spark.SparkKernel

So I tried manually extracting the java exec statement from the script file to see if I can run directly to make sure it was getting the right paths in the script, but that still failed, apparently the classpath is getting garbled along the way:

Here's what I tried:
$ /c/Progra~1/Java/jdk1.7.0_71/bin/java -cp /c/temp/kernel/current/lib/*; -Dprog.home=/c/temp/kernel/current -Dprog.version=0.1.5-SNAPSHOT com.ibm.spark.SparkKernel

and what it output:
Error: Could not find or load main class c:.temp.kernel.current.lib.akka-actor_2.10-2.3.11.jar
sh: -Dprog.home=/c/temp/kernel/current/: No such file or directory

Thoughts on diagnosing to get this running on windows for jupyter notebook (without resorting to VB) would be appreciated.

**Comment by chipsenkbeil** [comment]
Hm. So, I'm assuming that you have the kernel installed to /c/temp/kernel/<VERSION>/... and that the /c/temp/kernel/current/... is just pointing to that. Have you tried setting your classpath to a specific version?

E.g. For me on a Mac it would be `-cp /Users/senkwich/local/kernel/kernel-0.1.5-SNAPSHOT/lib`

**Comment by wtcooper** [comment]
Just tried again on home machine with cygwin.  First started with typical build instructions: sbt compile, sbt pack, make install, bin/sparkkernel, which leads to 

Failed to initialize compiler: object scala.runtime in compiler not found 

Similar to (https://github.com/ibm-et/spark-kernel/issues/132).  

Then tried manually typing in the java exec statement using the specific version as you suggested:

as mentioned above (java -cp /c/temp/kernel/<VERSION>/ -Drop.home=

**Comment by wtcooper** [comment]
Ended up building with cygwin (babun) using the added line to ScalaInterpreter.scala as in #132, this build fine.  Will put steps for other windows users in #132 comments.
