### ISSUE TITLE
Examples of sending spark code or jars using the REST interface

### ISSUE THREAD

**Issue by dimple2015** [ibm-et/spark-kernel#149]
Hi,
I'm looking for examples of sending scala Spark code or jars to the REST interface. What I'm trying here is to have 2 applications work on the same Spark Context. For example, I have app1 that loads data frame 1 and then app2 will try to access that same dataframe 1 by using the Spark context from the Spark kernel. 

Thanks
Dimple

**Comment by chipsenkbeil** [comment]
There is no REST interface on the Spark Kernel. If you are referring to a demo given earlier at a Spark meetup in the Bay Area, it was using a separate application that used the Spark Kernel client library to communicate with the Spark Kernel and provided a RESTful interface on top.

**Comment by dimple2015** [comment]
Yes, I was referring to the demo given at the meet up. Thanks.

Dimple
