### ISSUE TITLE
Dynamic namespaced interpreters.

### ISSUE THREAD

**Issue by nimbusgo** [ibm-et/spark-kernel#157]
One of the use cases I'm looking to support is multiple users having access to the same spark context through separate notebooks. For example, say you have a 1TB dataset that you want loaded in memory once, and then various users want to run arbitrary python, scala, sql, or r operations that depend on the same shared dataframe.

This is certainly possible now, but requires a fair amount of discipline on the part of the users. Since all code execution happens in the same interpreter for each language, users must be careful with their choice of definitions, or follow some pattern of namespacing so as not to interfere with each other.

It would be easier for users if each user could use their own interpreter, and perhaps even restart their interpreter if they want to. All without restarting the kernel, spark context or other users' interpreters.

I went and did a quick check to see if this is workable just with Pyspark: https://github.com/nimbusgo/spark-kernel/commit/7ca77756fc925a6f9c3ee48b36a6c4b78f4f6249

It seems to work fine. The existing functionality of the cell magic "%%PySpark" remains the same, but now you can also do "%%Pyspark bob" or "%%Pyspark sally" and now bob and sally are working with separate interpreters. If an interpreter with the same namespace string already exists, code is executed on that interpreter, otherwise a new interpreter is created and put in kernel.data.

A couple issues with this quick change that I noticed. To allow for an optional namespace argument (supporting both "%%PySpark" and "%%PySpark bob"), I removed the trim on this line: https://github.com/nimbusgo/spark-kernel/commit/7ca77756fc925a6f9c3ee48b36a6c4b78f4f6249#diff-5cc1dc2830d211c4fd181b8bba99d228L39
I'm not sure if there's a better way of doing that, or if other magics would be adversely affected by that change. I'm sure this could also be done in a cleaner fashion, perhaps by adapting ArgumentParsingSupport with better support for cell magics or adding a new trait for this purpose.

Also, it would probably make sense to add an additional line magic that can delete these dynamically created interpreters from kernel.data, perhaps in the form of "%DeleteInterpreter PySpark bob". Then users could effectively shutdown or restart their sessions.

If this functionality is workable than I'm optimistic about this working with an extension of the jupyter notebook. Basically, each notebook would connect to the same kernel, and each notebook would have an associated language and namespace string so that the appropriate cell magic "%%lang namespace" could be prepended to each non magic cell execution.

I realize that this does not address the whole picture of allowing users to create and restart isolated sessions using the same spark context. Any jars loaded will still get dumped to the same class server. However, I've got my eyes on a similar adjustment in core spark so that you could have selectable class servers/loaders on both driver/executor sides. Combined with multiple interpreters driver side, I see no reason why you couldn't have isolated restartable sessions against a long running spark context. In any case, just having separate interpreters driver side would achieve the desired effect for many users who won't be loading jars. If the envisioned change to core spark also happens at some point then this will be even better.

**Comment by lbustelo** [comment]
This is very nice experimentation. 

One concern that I have is that this solution does not horizontally scale. Although you can start many Python processes, you are ultimately flowing all spark work through the one jvm is that started the spark context. 

Basically this would work on a control set of users. I would not extend the notebook server so that all notebooks connect to the same kernel. Maybe have it be an option. 

Tachyon is a solution for sharing spark context. Not sure what is its status.

**Comment by nimbusgo** [comment]
Yes, this approach by itself will likely run into trouble when you get into 100+ concurrent users.

As you say, there are some alternatives to sharing access to cluster resources and in memory datasets. One alternative is to make use of tachyon, an in memory cluster filesystem. You persist datasets you want to share in tachyon and for interactive access each user uses their own short lived spark context. A user could execute a job or sql statement that depends on a dataset stored in tachyon and a sufficiently sized spark context could be brought up, execute the job, and turn off. You want to turn off the spark context each time because otherwise you're locking unutilized cluster resources to one user. However, there's a fair amount of overhead involved with starting a spark context for each interaction. One way to address this is to make use of dynamic allocation with mesos. So each user has an application with a defined maximum allocation of resources, but mesos takes away the resources when they're not being used and gives them to other applications that want them. Some issues with this are that the dynamic allocations are not without friction for the moment at least. You're also very likely to run into issues with data locality. If each user has a small to medium allocation of resources and they're running things that depend on large in memory datasets how do you guarantee that the computing allocation will overlap nicely with the in memory datasets? There's a fair bit of machinery that would need to be made to make the experience as convenient as just sharing the spark context. Also, I haven't seen or heard of anyone so far who's actually made this approach work for interactive access. I do think this is a great direction to pursue, but it seems farther off, and I think it's actually complementary to improvements in sharing a single spark context.

It's also useful to consider Databricks' approach. They're sharing a single spark context among 10+ concurrent notebooks. Not really sure how they're doing that precisely, but I imagine it's also something that doesn't completely scale horizontally either. It's still useful though, and better than having 1 user per context.

What I'm looking to do is find a nice middle ground that can improve access in the short-medium term. The architecture I'm considering is where you have a large shared cluster and you provide access through a set of gateway nodes. Each gateway node is running one spark kernel, that has one spark context, and also a notebook server attached to that single spark kernel. If a team of between 5 and 20 people can make use of the same gateway, that would be great. It would certainly improve the access over what's currently available, and it would be a reasonably efficient use of cluster resources to share 1 long interactive session among several users.

I'm also somewhat optimistic about being able to scale up to say, 100 users on one context. It's not clear to me yet what the bottleneck will be there, but I think an effective use of akka actors could get you pretty far. Also, the load on the spark context may not be that heavy if most users are just doing dataframe operations. As long as they're not streaming data through the driver, like say doing big collects or big broadcasts, it probably won't be that bad.

**Comment by nimbusgo** [comment]
I've thought of a better way to achieve the desired outcome. Basically you start a manager process that can bring up kernels on demand, but each kernel doesn't start its own spark context, they just share the same one via the SparkContext singleton all on the same jvm. I'll have more details later.
