### ISSUE TITLE
Execute result arrives after idle message

### ISSUE THREAD

**Issue by wellecks** [ibm-et/spark-kernel#161]
After code execution completes, the notebook may receive the kernel's `execute_request` message after receiving the `status: idle` message. This has led to the issue [jupyter/jupyter-js-services#44](https://github.com/jupyter/jupyter-js-services/issues/44). According to the comment in that issue, this is a protocol violation. The [protocol](http://jupyter-client.readthedocs.org/en/latest/messaging.html) may need to be updated to explicitly state that this is a requirement.

**Comment by wellecks** [comment]
Three messages get sent by the `ExecuteRequestHandler`: 

1. `execute_reply`
2. `execute_result`
3. `status` (see `BaseHandler`)

In `BaseHandler`, the intention was for the `status` to be sent after processing completed. However, it looks like the order in which the three messages get sent is not guaranteed; e.g. as it is currently implemented, message (3)  typically is sent before message (2), but adding a `Thread.sleep(1000)` before the status message is sent causes it to be sent (correctly) after messages (1) and (2)

**Comment by chipsenkbeil** [comment]
@welleck, does the ordered trait that @Lull3rSkat3r added to provide guaranteed message ordering between Akka actors not help here?

**Comment by wellecks** [comment]
The `OrderedSupport` helps with enforcing the order in which messages are processed, whereas this dealt with when the messages were sent.

It turns out that message (3) was getting sent _first_, since (1) and (2) were sent in the `executeFuture`'s `onComplete`, rather than a separate future that executes after `executeFuture`. Now (3) is sent after this separate future completes.

It ended up being a two-line change, but I added a test case as well
