### ISSUE TITLE
Add  APACHE_HADOOP_VERSION as an environment variable for build.

### ISSUE THREAD

**Issue by vinomaster** [ibm-et/spark-kernel#162]
In the same fashion as we currently handle Spark Version, we want to allow the user to override and specify the desired hadoop version. 

Current code is explicitly building with Hadoop version 2.3 as the default. Would like to override to build with 2.6.0

**Comment by chipsenkbeil** [comment]
Labelling as bug since this is prevent several users to be able to connect to their clusters due to a forced Hadoop version.
