### ISSUE TITLE
How do I configure the memory for spark-kernel?

### ISSUE THREAD

**Issue by jlamcanopy** [ibm-et/spark-kernel#165]
I want to know how I can configure the memory for spark-kernel. Thank you!

**Comment by lbustelo** [comment]
Se here for an example
https://github.com/ibm-et/spark-kernel/blob/master/Vagrantfile#L121

You basically send jvm settings on the JVM_OPT env variable. 

Gino B.

**Comment by jlamcanopy** [comment]
@lbustelo That works!
