### ISSUE TITLE
kernel.magics.addJar() returns jar not found

### ISSUE THREAD

**Issue by andrimirandi** [ibm-et/spark-kernel#167]
Hi, can someone please help me, I try to run the following codes in jupyter

    kernel.magics.addJar("file:/opt/spark/lib/commons-csv-1.2.jar");
    kernel.magics.addJar("file:/opt/spark/lib/spark-csv_2.11-1.2.0.jar");

but when i see the logs I get this errors

    15/10/19 23:35:06 [ERROR] o.a.s.SparkContext - Jar not found at /tmp/spark_kernel_add_jars2524856856038596772/commons-csv-1.2.jar
    res3: Either[com.ibm.spark.magic.CellMagicOutput,com.ibm.spark.magic.LineMagicOutput] = Right(())
    15/10/19 23:35:08 [ERROR] o.a.s.SparkContext - Jar not found at /tmp/spark_kernel_add_jars2524856856038596772/spark-csv_2.11-1.2.0.jar
    res4: Either[com.ibm.spark.magic.CellMagicOutput,com.ibm.spark.magic.LineMagicOutput] = Right(())

the weird thing is that the library exists there

    username@ubuntu:/opt/spark$ ls -l /tmp/spark_kernel_add_jars2524856856038596772/ 
    total 152
    -rw-r--r-- 1 username username  38795 Oct 19 23:35 commons-csv-1.2.jar
    -rw-r--r-- 1 username username 112631 Oct 19 23:35 spark-csv_2.11-1.2.0.jar

Thank you

**Comment by lbustelo** [comment]
Thanks, we'll take a look

**Comment by andrimirandi** [comment]
Thanks @lbustelo ,
I was wondering, should I want to add jars like spark-csv, are there any other way ?

Thanks

**Comment by lbustelo** [comment]
The main way to add hard is using the %addJar Magic. That basically calls the same code above. Give that a try because that works fine for us. 

In a cell run
%addJar file:/opt/spark/lib/commons-csv-1.2.jar

You can also try %addDeps

See https://github.com/ibm-et/spark-kernel/wiki/List-of-Current-Magics-for-the-Spark-Kernel

**Comment by andrimirandi** [comment]
Thanks @lbustelo
