### ISSUE TITLE
Integrate with jupyter-scala to get some niceties

### ISSUE THREAD

**Issue by ittayd** [ibm-et/spark-kernel#168]
jupyter-scala has some nice features, primarily I like load.ivy which can be used to easily load libraries and also uplot-highcharts (not in jupyter-scala, but from the same author), that can create nice graphs from the data

**Comment by lbustelo** [comment]
We will take a look at jupyter-scala. I'll close this and preferable have you open specific feature requests. 

Our %%AddDeps used ivy style dependencies syntax to download code.

**Comment by lbustelo** [comment]
Take a look at https://github.com/jupyter-incubator/declarativewidgets for examples of rich widgets that work on several lang kernels.
