### ISSUE TITLE
support verbatim xml in kernel.magics.html

### ISSUE THREAD

**Issue by ittayd** [ibm-et/spark-kernel#170]
It is much nicer to write 
kernel.magics.html(<div id={id}>hi</div>) than the string equivalent. I can currently write kernel.magics.html(<div id={id}>hi</div>.toString), but it would be nice if this verbosity were not required

**Comment by lbustelo** [comment]
I'm not sure I understand this one... maybe your example are getting destroyed by markdown.

You should be able to do something like below to make it seem that you are typing raw html.
```
kernel.magics.html(s"""
<div>
${somevar}
</div>
""");
```

or just use `%%html`

**Comment by lbustelo** [comment]
closing since no response
