### ISSUE TITLE
support InstallDep magic

### ISSUE THREAD

**Issue by ittayd** [ibm-et/spark-kernel#171]
Some experimental projects sometimes do not upload their jar to a maven repository. The, doing addjar in each session takes time. It would be nice if a jar could be copied to the maven repository (I can do it manually, but using a VM, so a bit combersome)

**Comment by lbustelo** [comment]
Not sure what you are asking for here... more details please!

**Comment by ittayd** [comment]
Say I have a jar in a URL. I don't want to keep downloading it. Instead I want to install to the local repository so it is read from it.

**Comment by lbustelo** [comment]
We cache the jar per kernel in AddJar. We also assume that each kernel may run remotely, so this may be out of scope for the goals of this project.
