### ISSUE TITLE
support line magic html/javascript

### ISSUE THREAD

**Issue by ittayd** [ibm-et/spark-kernel#172]
writing:
kernel.magic.html("<div>hi</div>)
1+2

in a cell returns 3, but doesn't insert the div. this means that if i want to create a div and then use javascript to populate it, I need to run this in two separate cells. the result is that the javascript's effect is in the previous cell, which is surprising

**Comment by lbustelo** [comment]
Not sure why you are using kernel.magic syntax and not the `%%html` magic. The `%%html` magic on the top of the cell allows you to just write HTML

**Comment by ittayd** [comment]
Yes, but what if the html is a result of calling utility methods? Then I don't want magic, but a proper scala call that will evaluate the parameters first

**Comment by lbustelo** [comment]
You should be able to do:

CELL 1 --------------------------
val content = someFunction()

CELL 2 --------------------------
kernel.magic.html(content)


It is key that a kernel.magic.html call is on its own cell. It may work if it is the last statement.

Additionally, we have a kernel.magic.javascript / %%javascript. 

You can also embed `<script>` in the html magic.

Is there anything else needed?

**Comment by lbustelo** [comment]
no response... closing this
