### ISSUE TITLE
If code returns value with newlines, nothing is printed in the output

### ISSUE THREAD

**Issue by ittayd** [ibm-et/spark-kernel#173]
In the below example I define 'foo' to once return a string and another time to return a string with \n. in the first time running it returns the expected result. In the second time no output is created (in jupyter-scala, the same example runs fine)

In [56]: def foo = {
 (1 to 2).toString
}
In [57]: foo
Out[57]: Range(1, 2)
In [58]: def foo = {
 (1 to 2).map(_ + "\n").toString
}
In [59]: foo
In [ ]:

Another small caveat compared to jupyter-scala. There I see a 'defined function foo' as a result of running the code making it more shell-like
​

**Comment by lbustelo** [comment]
> There I see a 'defined function foo' as a result of running the code making it more shell-like
We are trying to emulate the python kernel behavior when declaring functions and vals.

As for the print problem, we will look into that.

It actually is a problem with any string with a `\n`

Running a cell with 
```
"asdfasdfasd \n"
```
Causes the same problem

**Comment by chipsenkbeil** [comment]
@swelleck and @wangmiao1981 will be pairing on this.

**Comment by wangmiao1981** [comment]
I reproduced the problem and did some analysis. I found that the relay message: execute_result was not sent for the failed case; while for the successful case, it sent the execute_result to the frontend. In addition, I did see the results returned from Spark. So it is the issue when returning message to the frontend. I am trying to add some log to get further information. Or I can use Java's way to print out the backtrace in the log. I should be able to make some progress tomorrow.

**Comment by wangmiao1981** [comment]
Issue found:
In ScalaInterpreter.scala:
def truncateResult(result:String, showType:Boolean =false, noTruncate: Boolean = false): String = {} will generate "" result for multiple lines. This code is also used for the code (request). Therefore, if I remove the logic of dealing multiple lines, it prints result but it has a side effect (i.e., it also prints output when you define the function foo). I am trying to find out a solution for this now.

**Comment by wangmiao1981** [comment]
I checked in the fix for handling multiple lines in regular expression.

**Comment by chipsenkbeil** [comment]
@wangmiao1981, did you make a pull request for this one? Or check directly into master? Typically, we create a pull request that references the issue, which allows someone else to verify that the branch representing the pull request does indeed fix the issue. The person that verifies would then handle the merge.

**Comment by wangmiao1981** [comment]
Chip, sorry for mistakenly checking in to the master. 

Sean also pointed this out. I will create a pull request with Sean's suggestion on new tests.

Miao
