### ISSUE TITLE
HiveContext not created even when Hive jar added to classpath

### ISSUE THREAD

**Issue by chipsenkbeil** [ibm-et/spark-kernel#176]
As we all know, adding jars to the interpreter does not make them available outside of the interpreter's classpath, meaning that they do not affect normal kernel code.

The Spark Kernel has logic to check for a HiveContext class when instantiating the Spark SQL Context, just like how Apache Spark does its instantiation; however, there is currently no way to make the HiveContext available as using `%addjar` does not make the HiveContext class available for instantiation (and the instantiation happens on startup, anyway).

Furthermore, it seems like dropping the Hive jar into the lib directory of a pack still does not correctly create the HiveContext (even when the class is available in the interpreter) and creating one manually results in errors being thrown when using it.

The HiveContext has a lot of benefits over the standard Spark SQL one and would make the SQL magic much more powerful as you can load datasets purely via SQL and perform more operations.

**Comment by jlamcanopy** [comment]
FYI... I encountered the same issue. It is very important because the hql dialect is much more advance than sql in Spark SQL.

**Comment by chipsenkbeil** [comment]
This is now resolved thanks to #229.
