### ISSUE TITLE
plotting

### ISSUE THREAD

**Issue by glyfnet** [ibm-et/spark-kernel#178]
Is there a way to integrate WISP or any type of plotting within Jupyter (ipython) notebook on a spark-kernel page? If not, I would like to work on this integration, but am at a loss as to how to extend the current code base. Some quick pointers on where and how would be helpful.

**Comment by chipsenkbeil** [comment]
You can use [magics](https://github.com/ibm-et/spark-kernel/wiki/Guide-to-Developing-Magics-for-the-Spark-Kernel) to accomplish this, although no magic is provided with the kernel to perform plotting.

Basically, you want to write a magic that generates the plot either as html/css/javascript or an image such as a png. From there, it is the simple case of shipping back the result using the correct mime type.

**Comment by lbustelo** [comment]
This is outside of the scope of the kernel at the moment. Like @chipsenkbeil says above, you would need to create a magic for this or import some library (addJar) and then write the necessary code on a cell.

Another option is to use https://github.com/jupyter-incubator/declarativewidgets.
