### ISSUE TITLE
When will you allow outside contributors?

### ISSUE THREAD

**Issue by glyfnet** [ibm-et/spark-kernel#199]
I have a branch I would like to push and create a pull request. See issue https://github.com/ibm-et/spark-kernel/issues/169

**Comment by lbustelo** [comment]
The matter of outside contributions is getting worked out actively on our side. I would like to have some news in the coming weeks.

**Comment by lbustelo** [comment]
http://apache-incubator-general.996316.n3.nabble.com/DISCUSS-Spark-Kernel-Incubator-Proposal-td46862.html
