### ISSUE TITLE
nbformat v4

### ISSUE THREAD

**Issue by mathieu1** [ibm-et/spark-kernel#20]
With the final release of IPython 3 possibly getting close, it might be valuable to get up to speed with ipython `master`. I'm actually using the kernel on IPython `master`, with only a single annoyance: Whenever the notebook (auto)-saves, it throws an error 

    Notebook validation failed
    The save operation succeeded, but the notebook does not appear to be valid. The validation error was:
    Notebook Validation failed: u'name' is a required property:
    {}

The kernel throws

    Notebook JSON is invalid: u'name' is a required property
    Failed validating u'required' in schema[u'properties'][u'metadata'][u'properties'][u'language_info']:
        {u'description': u'Kernel information.',
         u'properties': {u'codemirror_mode': {u'description': u'The codemirror mode to use for code in this language.',
                                              u'oneOf': [{u'type': u'string'},
                                                         {u'type': u'object'}]},
                         u'file_extension': {u'description': u'The file extension for files in this language.',
                                             u'type': u'string'},
                         u'mimetype': {u'description': u'The mimetype corresponding to files in this language.',
                                       u'type': u'string'},
                         u'name': {u'description': u'The programming language which this kernel runs.',
                                   u'type': u'string'},
                         u'pygments_lexer': {u'description': u'The pygments lexer to use for code in this language.',
                                             u'type': u'string'}},
         u'required': [u'name'],
         u'type': u'object'}
    
    On instance[u'metadata'][u'language_info']:
        {}

Indeed, looking into `Edit > Edit notebook metadata` one finds out the following metadata

    {
      "kernelspec": {
        "name": "spark",
        "display_name": "Spark 1.1.0 (Scala 2.10.4)"
      },
      "language_info": {}
    }

The only thing missing to pass the validation is `"name":"scala"` inside `language_info`.
I wasn't able to impact this using `kernel.json`, so I assume this can be fixed by slightly modifying/adding a message in [Spark]KernelInfo[Reply] accordingly. Does that sound like a good thing to make happen?

**Comment by cjm5325** [comment]
Absolutely. I'll look into getting this fixed.

**Comment by cjm5325** [comment]
Fixed as of commit 3f4c22a562c73a4c9e299d9c189e716725ea3ed9
