### ISSUE TITLE
Use values from html forms in javascript or scala scripts

### ISSUE THREAD

**Issue by andreistankevich** [ibm-et/spark-kernel#204]
I use iPython with spark-kernel and I am able to create html form on iPython notebook by %%html magic or by kernel.magics.html. It is clear.

I can use something like this to use scala variable value in html
kernel.magics.html(s"""
<div>
${somevar}
</div>
""");

But how can I do vice versa, how can I use value from html inputs in my scala code? 

Could you give me some simple example?

**Comment by lbustelo** [comment]
Take a look at [declarative widgets](https://github.com/jupyter-incubator/declarativewidgets) work. That give you some simplified way to communicate between client ui and kernel code. 

An example can be found [here](http://jupyter.cloudet.xyz/notebooks/widgets/examples/urth-scala-widgets.ipynb)

The alternative would be to write some JavaScript and manually set comm channel. 

Gino B.

**Comment by andreistankevich** [comment]
I am right that declarativewidgets supports only Python 3.2 and it could not work because I have 3.5?

**Comment by lbustelo** [comment]
I'm assuming you are asking IPython. For that, it supports 3.2.x

Gino B.
