### ISSUE TITLE
Avoid publishing unnecessary jars

### ISSUE THREAD

**Issue by rcsenkbeil** [ibm-et/spark-kernel#21]
We should not be publishing jars for our common code (protocol/macros). Rather, that code should be automatically included in our main jars (client/kernel). This way, only the main dependencies need to be included.

E.g. Instead of this:

    libraryDependencies ++= Seq(
        "com.ibm.spark" %% "client" % "VERSION",
        "com.ibm.spark" %% "protocol" % "VERSION",
        "com.ibm.spark" %% "macros" % "VERSION"
    )

You should be able to do this:

    libraryDependencies += "com.ibm.spark" %% "client" % "VERSION"

I thought I remembered reading a way to not publish common code projects in an sbt multi-project and, instead, include the common code into projects using the dependency. What is the best/right way to do this? Thoughts?

**Comment by rcsenkbeil** [comment]
One case that may work is to add the dependencies as jar dependencies in the respective project _build.sbt_ files.

E.g. Client's _build.sbt_:

    libraryDependencies ++= Seq(
        "com.ibm.spark" %% "protocol" % "VERSION",
        "com.ibm.spark" %% "macros" % "VERSION"
    )

The problems with this are that 1) you need to continuously update _build.sbt_ files when new versions of the kernel/client are released and 2) the compilation/publish order is more tricky as I'm not sure if you can force the evaluation of the client's _build.sbt_ file to take place after compiling and publishing new versions of protocol and macros (this also leads to problems with keeping jars in sync).

It would _potentially_ be much nicer if we can bundle the common code with the main projects, unless that causes other issues? As long as there are no conflicting classes between the main projects - see Issue #14 - I would think this would be a good solution.

**Comment by rcsenkbeil** [comment]
Aha! I found where I read the ability to include the source/compiled code into other projects. It's recommended for macros during distribution: http://www.scala-sbt.org/0.13.0/docs/Detailed-Topics/Macro-Projects.html#distribution

**Comment by Lull3rSkat3r** [comment]
This is not valid. @rcsenkbeil and I verified you can include the client library and all transitive dependencies are included. This line is all that is needed for an application to consume the kernel client library:

```scala
libraryDependencies += "com.ibm.spark" %% "client" % "VERSION"
```
