### ISSUE TITLE
installation of spark class

### ISSUE THREAD

**Issue by aremirata** [ibm-et/spark-kernel#212]
Hi I want to install this package in my spark-kernel? How can I install this?

https://github.com/FurongHuang/SpectralLDA-TensorSpark

Thanks

**Comment by lbustelo** [comment]
There are several ways to add packages to the kernel. See https://github.com/ibm-et/spark-kernel/wiki/List-of-Current-Magics-for-the-Spark-Kernel

Gino B.

**Comment by aremirata** [comment]
I always get this error
Name: java.net.MalformedURLException
Message: no protocol: '/Users/user/Desktop/spectrallda-tensor.jar'

What's the reason for this error and how can I solve this?

**Comment by aremirata** [comment]
This is now resolved.Thank you so much for your help.
