### ISSUE TITLE
New build refactor breaks my project

### ISSUE THREAD

**Issue by ReeceRobinson** [ibm-et/spark-kernel#218]
Hi,

I depend on this project as a component of a big data environment running in docker and now my build is broken as of the latest refactor of the build. The build seems to assume the users of this project use it stand-alone and not as a part of a larger system. I have to customise the dependencies to suite my use case. My build system is configured in a vagrant box so launching a vagrant image within my build vagrant image does not work.

Any advice on how to build this project without vagrant? Alternatively are there any detailed instructions on how to "install" this kernel within an existing jupyter deployment?

I really like this project and would like to continue to use it.

Regards
Reece

**Comment by lbustelo** [comment]
we will continue to us make as our entry point for building. The pr #220 is going to change so make calls any directly and not rely on vagrant. 

That should get you going again.

**Comment by ReeceRobinson** [comment]
Great. Thanks for that.

**Comment by lbustelo** [comment]
Makefile changes have been merged... please verify that they will work for you and if so, close.

Thanks.

**Comment by ReeceRobinson** [comment]
Thanks for that. Can you help me figure out how to modify my old build command?

To build my custom docker image I used to use the following in my Dockerfile:
RUN cd spark-kernel && sbt compile && sbt pack
RUN (cd spark-kernel/kernel/target/pack && make install)
This worked fine.

What is the equivalent now?

**Comment by lbustelo** [comment]
The equivalent is to do
RUN cd spark-kernel && make dist

Then gave the kernel.json run spark-kernel/dist/spark-kernel/bin/spark-kernel

**Comment by lbustelo** [comment]
@ReeceRobinson No news, good news?

**Comment by lbustelo** [comment]
Closing this... if any issues are still there, then another issue can get filed.
