### ISSUE TITLE
SQL context missing in global namespace

### ISSUE THREAD

**Issue by chipsenkbeil** [ibm-et/spark-kernel#223]
Previously, we had `sc` as the SparkContext and `sqlContext` as the SQLContext available to the user. It looks like the SQLContext is missing from the global namespace now.

Both are available off of the _kernel_ object as `kernel.sparkContext` and `kernel.sqlContext` respectively.

**Comment by lbustelo** [comment]
I think this one is high priority...

**Comment by chipsenkbeil** [comment]
Current code is here: github.com/ibm-et/spark-kernel/blob/master/kernel/src/main/scala/com/ibm/spark/kernel/api/Kernel.scala#L332

There is a line in the same function that adds the SparkContext. So, we need to do the same with the `sqlContext`.

**Comment by chipsenkbeil** [comment]
Method that does this is still here, actually: https://github.com/ibm-et/spark-kernel/blob/45e451a5691bf7f4a30f69dbbba3e6651006b580/kernel/src/main/scala/com/ibm/spark/boot/layer/ComponentInitialization.scala#L158

**Comment by chipsenkbeil** [comment]
Furthermore, our logic to create a HiveContext was lost. The method is still here: https://github.com/ibm-et/spark-kernel/blob/45e451a5691bf7f4a30f69dbbba3e6651006b580/kernel/src/main/scala/com/ibm/spark/boot/layer/ComponentInitialization.scala#L131
