### ISSUE TITLE
Assembly jar added to cluster many times on startup

### ISSUE THREAD

**Issue by chipsenkbeil** [ibm-et/spark-kernel#224]
![screen shot 2015-12-03 at 9 42 47 am](https://cloud.githubusercontent.com/assets/2481802/11565683/9ff5ac20-99a4-11e5-9988-afa367a09f0f.png)

This is due to old code that added the jar of each module:
https://github.com/ibm-et/spark-kernel/blob/master/kernel/src/main/scala/com/ibm/spark/kernel/api/Kernel.scala#L442

Now, we should only need to add the jar once since all modules for the kernel are in the assembly jar. Furthermore, as mentioned by @lbustelo, Spark Submit might add the jar for us, so this code might not be necessary anymore. We need to verify that.

**Comment by lbustelo** [comment]
working on this...
