### ISSUE TITLE
connecting hive context with spark-kernel

### ISSUE THREAD

**Issue by aremirata** [ibm-et/spark-kernel#235]
I have a data found on hive context in hadoop. I want to process the data using the scala API through spark-kernel. How can I connect the spark context to the hive context? In Pyspark, I can do this: https://fossies.org/diffs/spark/1.3.1_vs_1.4.0/python/pyspark/shell.py-diff.html. Is there a similar process we can do for the scala API?

**Comment by lbustelo** [comment]
The link does not work, but there should be nothing special about it. You have a val called 'sc' already. That is your context. You can create the other context out of that as normal. 

Gino B.

**Comment by chipsenkbeil** [comment]
I see this on the page:

![screen shot 2015-12-20 at 9 05 03 am](https://cloud.githubusercontent.com/assets/2481802/11918481/d1ef84ec-a6f8-11e5-96bf-04ab9967d4b4.png)

Looks like the logic is to create a HiveContext if possible, otherwise using a SQLContext with regard to PySpark?

This should happen when #166 is resolved. When you use Scala, you now get a HiveContext when it is available in your `SPARK_HOME`. However, since PySpark and SparkR do not have that SQLContext, they are creating a normal one. So, once we link the Scala SQLContext, you will have access to a HiveContext if it is available.

**Comment by aremirata** [comment]
Hi guys, thanks for the replies. I cannot find org.apache.spark.sql.hive. How can I add this to the spark-kernel. Is there a jar file for the hive context that we can use?

**Comment by aremirata** [comment]
Based to this post, https://github.com/ibm-et/spark-kernel/pull/229, if we're not going to use vagrant, is there a way we can use the HiveContext?

**Comment by chipsenkbeil** [comment]
@aremirata, you don't need to use vagrant to get the HiveContext. I was merely pointing out that the HiveContext started to get picked up. You just need to make sure that the Spark distribution referenced in `SPARK_HOME` has Hive available. I think the standard distribution has it.

**Comment by aremirata** [comment]
@chipsenkbeil, i cannot import org.apache.spark.sql.hive.HiveContext. It says that hive is not a member of the package org.apache.spark.sql. Yes, there is hive available on the Spark distribution referenced in my SPARK_HOME.

**Comment by chipsenkbeil** [comment]
@aremirata, are you using Scala? Or is this PySpark or SparkR?

**Comment by aremirata** [comment]
I'm using scala

**Comment by chipsenkbeil** [comment]
Just to make sure, you verified that the SQLContext available in Scala is not a HiveContext?

![99298dba-9da7-11e5-912a-3431a77aad8d](https://cloud.githubusercontent.com/assets/2481802/11947537/e9fb9d10-a82d-11e5-9d98-d54a99ce678c.png)

If you're using Scala and pointing to a Spark distribution with Hive available, you should get a HiveContext. As for importing `org.apache.spark.sql.hive.HiveContext`, there may be a bug with the compiler class path and runtime classloader if you have a HiveContext but cannot reference the class at compile time.

**Comment by aremirata** [comment]
@chipsenkbeil , here's what I have done to point on the spark cluster:

import java.util.Random
import org.apache.log4j.Logger
import org.apache.log4j.Level
import scala.io.Source
import org.apache.spark.SparkConf
import org.apache.spark.SparkContext
import org.apache.spark.SparkContext._
import org.apache.spark.rdd._

val sparkHome = "/opt/spark/current"
val master = "spark://xxx.xxx.xx.xxx:xxxx"

val conf = new SparkConf().setAppName("Scala Notebook").setMaster(master).setSparkHome(sparkHome).set("spark.executor.memory", "624g").set("spark.driver.allowMultipleContexts", "true") 

val sc = new SparkContext(conf)

val sqlContext = new org.apache.spark.sql.SQLContext(sc)

when I call sqlContext, I am being returned with SQLContext and not with the HiveContext

**Comment by chipsenkbeil** [comment]
Oh, that explains it. With the Spark Kernel, you do _NOT_ create the SparkContext or SQLContext yourself. Both of those are provided for you. The SparkContext is available as `sc` and the SQLContext (or HiveContext) as `sqlContext`.

If you need to pass options to the SparkContext, you can provide them via command line or environment variables. You need to provide SPARK_HOME when running the kernel, not programmatically.

**Comment by aremirata** [comment]
@chipsenkbeil . Thank you so much for helping. Sorry I'm new to Spark. Can I elaborate more on this line:

"If you need to pass options to the SparkContext, you can provide them via command line or environment variables. You need to provide SPARK_HOME when running the kernel, not programmatically."

**Comment by chipsenkbeil** [comment]
@aremirata, everyone has to start somewhere, so don't worry about it!

So, here is an example of my `kernel.json` file:

```json
{
    "display_name": "Spark 1.5.1 (Scala 2.10.4)",
    "language_info": { "name": "scala" },
    "argv": [
        "/src/spark-kernel/dist/spark-kernel/bin/spark-kernel",
        "--profile",
        "{connection_file}"
    ],
    "codemirror_mode": "scala",
    "env": {
        "MAX_INTERPRETER_THREADS": "16",
        "SPARK_OPTS": "--master=local[2] --driver-java-options=-Xms1024M --driver-java-options=-Xmx4096M --driver-java-options=-Dlog4j.logLevel=trace",
        "CAPTURE_STANDARD_OUT": "true",
        "CAPTURE_STANDARD_ERR": "true",
        "SEND_EMPTY_OUTPUT": "false",
        "SPARK_HOME": "/opt/spark",
        "PYTHONPATH": "/opt/spark/python:/opt/spark/python/lib/py4j-0.8.2.1-src.zip"
     }
}
```

Notice that I am providing `SPARK_HOME` as an environment variable ad providing Spark options through the `SPARK_OPTS` environment variable. I've also got `PYTHONPATH` set so I can use PySpark properly. These environment variables are passed to the Spark Kernel when it is started.

**Comment by aremirata** [comment]
@chipsenkbeil , thanks for your detailed reply, I followed your example and change the Spark options 
--master = spark://xxx.xxx.xx.xxx:xxxx, however when I run sc.master on the spark-kernel, this is still pointing locally, Aside from kernel.json, is there another file I have to edit to point my SPARK_HOME to the hadoop cluster? After editing kernel.json, does it automatically follow that upon starting the kernel, the options I have set on the kernel.json reflects?

**Comment by aremirata** [comment]
@chipsenkbeil , may

**Comment by aremirata** [comment]
This is now solved. We install the packages needed across all the nodes of the cluster. Thank you so much for all your help.
