### ISSUE TITLE
Will spark kernel work with Spark 1.6?

### ISSUE THREAD

**Issue by pberkland** [ibm-et/spark-kernel#241]

**Comment by mikeivanov** [comment]
I just have tried it with 1.6 - works perfectly fine. I had to update the Makefile, though: 
-APACHE_SPARK_VERSION?=1.5.1
+APACHE_SPARK_VERSION?=1.6.0

**Comment by lbustelo** [comment]
No need to modify the Makefile... the version is also picked up from env variable `APACHE_SPARK_VERSION`

**Comment by lbustelo** [comment]
slight update to README added to mention support of 1.5.1+
