### ISSUE TITLE
Debugging “Wrong FS expected: file:///” exception from HDFS

### ISSUE THREAD

**Issue by aremirata** [ibm-et/spark-kernel#242]
Is there a way we can edit the conf settings in Spark Kernel?

Equivalent to these lines:

// pickup config files off classpath
 Configuration conf = new Configuration()
 // explicitely add other config files
 conf.addResource("/home/hadoop/conf/core-site.xml");
 // create a FileSystem object needed to load file resources
 FileSystem fs = FileSystem.get(conf);
 // load files and stuff below!

Thanks a lot!

I get an error in my checkpointing for ALS and the error says that 

Name: java.lang.IllegralArgumentException
Message: Wrong FS: hdfs:[url+ directory], expected: file:///

According to this post http://opensourceconnections.com/blog/2013/03/24/hdfs-debugging-wrong-fs-expected-file-exception/, it can be solved by following the three lines of codes above. How can we get this implemented in Spark

**Comment by chipsenkbeil** [comment]
Isn't that Hadoop configuration settings? I can't remember if `sc.hadoopConfiguration` is modifiable. Based on the [Scaladoc description](https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.SparkContext), I think any changes to it act as global Hadoop configuration changes. Have you tried doing...

```scala
val conf = sc.hadoopConfiguration
conf.addResource("/home/hadoop/conf/core-site.xml")
val fs = FileSystem.get(conf)
```

Or, if you just want to naturally inherit Hadoop configuration files, have you seen this documentation? https://spark.apache.org/docs/latest/configuration.html#inheriting-hadoop-cluster-configuration

**Comment by aremirata** [comment]
Hi @chipsenkbeil . Thank you so much for the help. I have now solve this problem. 
What I did is follow Inheriting Hadoop cluster configuration on this documentation.
https://spark.apache.org/docs/latest/configuration.html#inheriting-hadoop-cluster-configuration
It suggested that I have to put two hadoop config files namely core-site.xml and hdfs-site.xml in the Spark classpath. But according to this documentation(even though this is old, the suggestion worked): https://spark.apache.org/docs/0.9.1/hadoop-third-party-distributions.html
"You can copy these files into $SPARK_HOME/conf and they will be included in Spark’s classpath automatically.". Thanks for giving me idea about inheriting Hadoop configuration files.
