### ISSUE TITLE
IvyDependencyDownloader ignores repositoryUrl 

### ISSUE THREAD

**Issue by kmader** [ibm-et/spark-kernel#246]
The ```class IvyDependencyDownloader(repositoryUrl: String, baseDirectory: String)``` takes a URL as an argument but only uses ```IBiblioResolver``` and does nothing with the ``repositoryUrl```. It uses only the central maven repository.

In the current project
https://github.com/ibm-et/spark-kernel/blob/master/kernel-api/src/main/scala/com/ibm/spark/dependencies/IvyDependencyDownloader.scala#L39

from the new project (after refactoring)
https://github.com/apache/incubator-toree/blob/0a5a7f6bac1afcb0a410887f17112b0d98bbcd68/kernel-api/src/main/scala/com/ibm/spark/dependencies/IvyDependencyDownloader.scala#L39

I posted here since there is no official JIRA project yet (https://issues.apache.org/jira/browse/INFRA-11082)

**Comment by lbustelo** [comment]
This now has a Jira... closing
