### ISSUE TITLE
Use of matplotlib embedded graphics with pyspark in the Scala Kernel

### ISSUE THREAD

**Issue by aimr** [ibm-et/spark-kernel#248]
With the Spark 1.5.1 (Scala 2.10.4) kernel I am trying to combine data processing with Spark/Scala in some cells, and visualization with python (via the magic %%pyspark) in other cells of the same notebook.

If I use a notebook with the PySpark Kernel, the use of the magic "%matplotlib inline" works like a charm (see file attached). However, if I try to do it the same in the spark/scala default kernel in a cell with the %%pyspark magic, it does not recognize it, although the import matplotlib works fine, and produces plots, but in a separated window.

![image](https://cloud.githubusercontent.com/assets/17050039/12790776/433d8d46-caa4-11e5-8b02-b1ee4f869f6c.png)

**Comment by lbustelo** [comment]
The matplotlib Magic is not available in spark kernel. It is not part is pyspark, it is an extension to the python kernel that ships with Jupyter.

**Comment by lbustelo** [comment]
Be aware that this project has moved to Apache Toree.
