### ISSUE TITLE
Timeouts are too short for some tests

### ISSUE THREAD

**Issue by cjm5325** [ibm-et/spark-kernel#27]
For some tests i.e. CommMsgHandlerSpec.scala and ExecuteRequestHandlerSpec.scala they do some
```scala
probe.receive(some_timeout)
```
and the timeouts seem to be too short, resulting in erroneous test failures. This happens in the context of a `sbt test` and not in an IDE.

**Comment by rcsenkbeil** [comment]
What environment are you using to run the tests? Vagrant? Docker? Host machine? What memory constraints are you giving to sbt?

**Comment by cjm5325** [comment]
In vagrant running `sbt test` with `SBT_OPTS` (and also tried `JVM_OPTS`) set to those recommended [in the "Building from Source" docs](https://github.com/ibm-et/spark-kernel/wiki/Building-from-Source#compile-source).

I also run out of memory on my host with 16gb and have to run each project's tests with `sbt kernel/test`, `sbt kernel-api/test`, etc.

**Comment by rcsenkbeil** [comment]
I haven't been able to reproduce these errors, although the vagrant box does seem to have issue with three of the tests from `KernelCommSpecForSystem`.

There is an option to dilate functions, scaling them by a factor of X.

> The tight timeouts you use during testing on your lightning-fast notebook will invariably lead to spurious test failures on the heavily loaded Jenkins server (or similar). To account for this situation, all maximum durations are internally scaled by a factor taken from the Configuration, akka.test.timefactor, which defaults to 1.

The problems with your host machine are bizarre. Have you tried upping the maximum size from `2048M`?

**Comment by rcsenkbeil** [comment]
Failed Travis CI to back this:

![screen shot 2015-01-26 at 11 53 20 am](https://cloud.githubusercontent.com/assets/2481802/5904950/0ad30602-a552-11e4-89a8-943f8f750c4a.png)

**Comment by lbustelo** [comment]
This is a dup of #74
