### ISSUE TITLE
Remove docs/ directory

### ISSUE THREAD

**Issue by rcsenkbeil** [ibm-et/spark-kernel#28]
As we have moved our docs to the wiki, I believe the `docs/` directory and the markdown files inside should be removed.

I've already captured the images from the keynote as PNGs and included them in the wiki repository, but we might want to make a backup of that elsewhere.

**Comment by lbustelo** [comment]
I suggest you leave the keynote there and treat it as source in case you need to modify or add diagrams later on. 

Gino B.

**Comment by rcsenkbeil** [comment]
@lbustelo  Someone suggested moving it to the wiki repository. That way, we still have it available in Git, but it isn't in our kernel's source code repository. Plus, it means we can refer to it with a relative URL in the wiki if we want to provide a download link. What are your thoughts on that?

**Comment by lbustelo** [comment]
The big gain is really avoiding bringing down the large keynote on initial checkout. For that reason, I would say fine, move it out but keep it around close in case we need it for new diagrams. 

Gino B.
