### ISSUE TITLE
Magic usage information is printed out of order

### ISSUE THREAD

**Issue by cjm5325** [ibm-et/spark-kernel#32]
Magic usage information is printed out of order because the `println(...)`'s which print the usage information are sent asynchronously and arrive at different times. I think the exact behavior is that any text printed is broken up on newline and sent immediately, but I need to investigate more.

Most of the time things are fine:
![correct](https://cloud.githubusercontent.com/assets/9045199/5783330/81c36d9c-9d87-11e4-9b8b-143975b069e7.png)

...but some times it's out of order:

![incorrect](https://cloud.githubusercontent.com/assets/9045199/5783434/6e2c1bde-9d88-11e4-8188-d9bb8a9762b0.png)

**Comment by rcsenkbeil** [comment]
You can find the exact behavior here: https://github.com/ibm-et/spark-kernel/blob/master/kernel/src/main/scala/com/ibm/spark/kernel/protocol/v5/stream/KernelMessageStream.scala#L79

I believe there was discussion regarding akka messages being out of order unless given a different dispatcher. Did we ever switch the dispatcher for the actors used by the KernelMessageStream? If we did, it might be a networking issue instead.

**Comment by Lull3rSkat3r** [comment]
The dispatcher is setup, but the guaranteed ordering does not apply to all actors just by changing the underlying dispatcher. There is a trait called [OrderedSupport](https://github.com/ibm-et/spark-kernel/blob/master/kernel/src/main/scala/com/ibm/spark/kernel/protocol/v5/OrderedSupport.scala) which enables this type of behavior for actors. An example usage of the trait is [KernelMessageRelay](https://github.com/ibm-et/spark-kernel/blob/870a652c1fe094fba2aa9ed83e684bd8562b83cc/kernel/src/main/scala/com/ibm/spark/kernel/protocol/v5/relay/KernelMessageRelay.scala)

**Comment by rcsenkbeil** [comment]
Verified that we are sending the messages in the correct order via KernelMessageStream. Next, going to check if the KernelMessageRelay is receiving the messages in the right order. If so, I'll lastly check if the messages are received by the IOPub actor in the right order.

![screen shot 2015-01-19 at 4 40 57 pm](https://cloud.githubusercontent.com/assets/2481802/5809080/1662ab9c-9ffa-11e4-92ce-e5ff27ec55d3.png)

**Comment by rcsenkbeil** [comment]
After a quick run through, I think the messages are exiting the kernel out of order.

The messages appear to enter the KernelMessageRelay in correct order:
![screen shot 2015-01-20 at 10 06 30 am](https://cloud.githubusercontent.com/assets/2481802/5821030/c4ed07d6-a08e-11e4-8176-c57085c7f707.png)

However, stream messages exiting through the IOPub socket actor are out of sync:
![screen shot 2015-01-20 at 10 17 18 am](https://cloud.githubusercontent.com/assets/2481802/5821040/d45a1db2-a08e-11e4-9b9d-c750601c4c83.png)

Going to look into adding OrderedSupport to the IOPub actor.

**Comment by rcsenkbeil** [comment]
Ordering does not fully fix the issue. After discussion with @Lull3rSkat3r, I'm going to implement a periodic flushing mechanism to reduce the amount of messages sent.
