### ISSUE TITLE
Kernel Client Should Notify When Code Execution Is Completed

### ISSUE THREAD

**Issue by Lull3rSkat3r** [ibm-et/spark-kernel#45]
At the moment, it is hard for users of the kernel client to determine when code execution is completed. This is partially due to the nature of the kernel client API, but also because ExecuteResult messages are not sent if their result is empty. 

We should add a method for users to hook into upon completion of code execution. I believe this method should only be invoked when the code has completed successfully. If users need notification about errors the `onError` method should suffice. The API should be something along the lines of:

```scala
client.execute("some code").onSuccessfulCompletion {
   println("Code executed successfully")
}
```

**Comment by rcsenkbeil** [comment]
@Lull3rSkat3r, I'm assuming this should be closed based on the merged PR?

**Comment by Lull3rSkat3r** [comment]
Yes, this should have been close with the PR.
