### ISSUE TITLE
Stay in sync with IPython 3.0 kernel_info_reply

### ISSUE THREAD

**Issue by rcsenkbeil** [ibm-et/spark-kernel#48]
I believe we are out of sync with IPython's kernel_info_reply. I don't remember the language_info containing fields like pygments nor do I remember the help_links section being there. I think they decided to move that information from the kernel.json, which is a bit of a disappointment to me.

Can someone verify this? @cjm5325 or @wellecks?

>    Message type: kernel_info_reply:
>
>     content = {
>        # Version of messaging protocol.
>        # The first integer indicates major version.  It is incremented when
>        # there is any backward incompatible change.
>        # The second integer indicates minor version.  It is incremented when
>        # there is any backward compatible change.
>        'protocol_version': 'X.Y.Z',
>
>        # The kernel implementation name
>        # (e.g. 'ipython' for the IPython kernel)
>        'implementation': str,
>
>        # Implementation version number.
>        # The version number of the kernel's implementation
>        # (e.g. IPython.__version__ for the IPython kernel)
>        'implementation_version': 'X.Y.Z',
>
>        # Programming language in which kernel is implemented.
>        # Kernel included in IPython returns 'python'.
>        'language': str,
>
>        # Language version number.
>        # It is Python version number (e.g., '2.7.3') for the kernel
>        # included in IPython.
>        'language_version': 'X.Y.Z',
>
>        # Information about the language of code for the kernel
>        'language_info': {
>            'mimetype': str,
>
>            # Pygments lexer, for highlighting
>            # Only needed if it differs from the top level 'language' field.
>            'pygments_lexer': str,
>
>            # Codemirror mode, for for highlighting in the notebook.
>            # Only needed if it differs from the top level 'language' field.
>            'codemirror_mode': str or dict,
>        },
>
>        # A banner of information about the kernel,
>        # which may be desplayed in console environments.
>        'banner' : str,
>
>        # Optional: A list of dictionaries, each with keys 'text' and 'url'.
>        # These will be displayed in the help menu in the notebook UI.
>        'help_links': [
>            {'text': str, 'url': str}
>        ],
>     }
>

**Comment by wellecks** [comment]
"help_links" isn't in our `KernelInfoReply` so it does look like that's a new field. Looks like there's also a "language" field that's not in our `KernelInfoReply`.

I also haven't seen "pygments_lexer" before; if we need it then it could added since we store the `language_info` as a `Map[String, String]`.

**Comment by wellecks** [comment]
For the full change details see:
https://github.com/ipython/ipython/commit/b4a3f46c790a01f1033a519a09f81aeb4755ed50

https://github.com/ipython/ipython/commit/5cf9dbf2d6af5b3c0a5de637603bdfc3cc016eab

https://github.com/ipython/ipython/commit/3684b661df1620710fc5fd75b4052f92831fad20

**Comment by rcsenkbeil** [comment]
We have verified that our current implementation works for IPython 3.0.0. I'm going to close this.
