### ISSUE TITLE
Connecting to the Spark Kernel with the Client Library not return any results.

### ISSUE THREAD

**Issue by Anne623** [ibm-et/spark-kernel#69]
hi, I try connet spark kernel with client , I try DocumentationExamples.scala, But nothing return.May be some configure are set wrong, below is logs with Spark-kernel starting and client runing. Thank you. :)

I start Spark kernel logs:
anne:~ # /root/local/bin/sparkkernel --iopub-port 43463
15/02/04 12:07:40 [INFO] c.i.s.SparkKernel$$anon$1 - Kernel version: 0.1.1-SNAPSHOT
15/02/04 12:07:40 [INFO] c.i.s.SparkKernel$$anon$1 - Scala version: 2.10.4
15/02/04 12:07:40 [INFO] c.i.s.SparkKernel$$anon$1 - Initializing internal actor system
15/02/04 12:07:40 [INFO] c.i.s.SparkKernel$$anon$1 - Connection Profile: {
  "stdin_port" : 48691,
  "control_port" : 44808,
  "hb_port" : 49691,
  "shell_port" : 40544,
  "iopub_port" : 43463,
  "ip" : "127.0.0.1",
  "transport" : "tcp",
  "signature_scheme" : "hmac-sha256",
  "key" : ""
}
15/02/04 12:07:40 [INFO] c.i.s.SparkKernel$$anon$1 - Constructing interpreter with arguments: 
15/02/04 12:07:44 [INFO] c.i.s.SparkKernel$$anon$1 - Constructing interpreter with arguments: 
15/02/04 12:07:45 [INFO] c.i.s.SparkKernel$$anon$1 - Using local[*] as Spark Master
15/02/04 12:07:45 [INFO] c.i.s.SparkKernel$$anon$1 - Using IBM Spark Kernel as Spark application name
15/02/04 12:07:45 [WARN] c.i.s.SparkKernel$$anon$1 - spark.executor.uri is not supported!
15/02/04 12:07:45 [WARN] c.i.s.SparkKernel$$anon$1 - Spark Home is not supported!
15/02/04 12:07:45 [WARN] c.i.s.SparkKernel$$anon$1 - Locked to Scala interpreter with SparkIMain until decoupled!
15/02/04 12:07:45 [WARN] c.i.s.SparkKernel$$anon$1 - Unable to control initialization of REPL class server!
15/02/04 12:07:45 [INFO] c.i.s.SparkKernel$$anon$1 - REPL Class Server Uri: http://xxxxx(Modified):52135
15/02/04 12:07:45 [INFO] Remoting - Starting remoting
15/02/04 12:07:45 [INFO] Remoting - Remoting started; listening on addresses :[akka.tcp://sparkDriver@anne:60272]
15/02/04 12:07:45 [INFO] Remoting - Remoting now listens on addresses: [akka.tcp://sparkDriver@anne:60272]
15/02/04 12:07:48 [INFO] c.i.s.SparkKernel$$anon$1 - Running in local mode! Not adding self as dependency!
15/02/04 12:07:49 [WARN] c.i.s.SparkKernel$$anon$1 - No external magics provided to MagicLoader!
kernel: com.ibm.spark.kernel.api.Kernel = com.ibm.spark.kernel.api.Kernel@4244e1f1
15/02/04 12:07:49 [INFO] c.i.s.SparkKernel$$anon$1 - Marking relay as ready for receiving messages
15/02/04 12:07:49 [INFO] c.i.s.k.p.v.r.KernelMessageRelay - Unstashing all messages received!
15/02/04 12:07:49 [INFO] c.i.s.k.p.v.r.KernelMessageRelay - Relay is now fully ready to receive messages!

And I run DocumentationExamples.scala logs below:

[info] Running com.anne.DocumentationExamples 

  {
    "stdin_port" : 48691,
  "control_port" : 44808,
  "hb_port" : 49691,
  "shell_port" : 40544,
  "iopub_port" : 43463,
  "ip" : "127.0.0.1",
  "transport" : "tcp",
  "signature_scheme" : "hmac-sha256",
  "key" : ""
  }
                            
15/02/04 15:13:18 [INFO] c.h.d.DocumentationExamples$$anon$1 - Creating execute_request handler
DeferredExecution()
15/02/04 15:13:18 [INFO] c.i.s.k.p.v.c.s.IOPubClient - Created IOPub socket
15/02/04 15:14:00 [INFO] c.i.s.k.p.v.c.SparkKernelClient - Shutting down client

**Comment by rcsenkbeil** [comment]
What operating system are you using? Did you make sure to install the binary dependency (libzmq)?

**Comment by Anne623** [comment]
@rcsenkbeil  My os is SUSE Linux Enterprise Server 11 SP1  (x86_64), and install the binary:
anne:~# rpm -qa | grep zmq
libczmq1-1.2.0-5.1
libzmq3-3.2.2-13.1
libczmq1-devel-1.2.0-5.1

**Comment by rcsenkbeil** [comment]
I notice that you have libzmq 3.2.2 installed. Currently, the Spark Kernel needs version 2 of ZeroMQ.

According to the documentation [here](http://zeromq.org/distro:sles), you can install version 2.2 of libzmq via something __similiar to__ following:

    zypper -p http://download.opensuse.org/repositories/home:/fengshuo:/zeromq/SLE_11_SP2/ -v in zeromq

Try switch ZeroMQ versions. I have not worked with czmq, so I do not know if that would conflict (I do not think it would).

**Comment by Anne623** [comment]
@rcsenkbeil Thank you, I install version 2.2 of libzmq, And it's working. The result print correctly.
