### ISSUE TITLE
How to set Spark Master executor cores when starting spark-kernel

### ISSUE THREAD

**Issue by Anne623** [ibm-et/spark-kernel#70]
Hi ,All,  I starting spark-kernel with spark-master standalone model, Now the spark-kernel will use all of the cores. 
```shell
anne:~ # /root/local/bin/sparkkernel --master=spark://xx.xxx.xxx.xxx:7077
```
the logs below:
```console
15/02/06 11:55:59 [INFO] c.i.s.SparkKernel$$anon$1 - Constructing interpreter with arguments: 
15/02/06 11:56:00 [INFO] c.i.s.SparkKernel$$anon$1 - Using spark://xx.xxx.xxx.xxx:7077 as Spark Master
```
The machine cores is 40.
```console
Id	Address	State	Cores	Memory
worker-20150204130337-anne18-60333	anne:60333	ALIVE	40 (40 Used)	377.5 GB (512.0 MB Used)
```

while spark kenel use 40 
```console

ID	Name	Cores	Memory per Node	Submitted Time	User	State	Duration
app-20150207032900-0009	IBM Spark Kernel	40	512.0 MB	2015/02/07 03:29:00	root	RUNNING	0.4 s
```

I have set spark.cores.max in spark-defaults.conf, But it's not working , once i starting spark-kernel,other application has no resource to run.

**Comment by rcsenkbeil** [comment]
The Spark Kernel currently does not have a way to specify the options __unless__ you use the Java property options. In your case, you want to run with `-Dspark.cores.max=xxx` to set the Spark property for maximum cores on standalone/Mesos coarse-grained.

To do this from the Spark Kernel script that is generated from `sbt pack`, you currently have to provide the options through the `JVM_OPT` environment variable.

In your case, it would look like this (if you're using bash as your shell):

    # JVM_OPT="-Dspark.cores.max=xxx" /root/local/bin/sparkkernel --master=spark://xx.xxx.xxx.xxx:7077

This is an oversight on our part. I'm going to tackle adding the ability to set these options outside of the JVM_OPT environment variable. See issue #71.

**Comment by rcsenkbeil** [comment]
If you grab the latest Spark Kernel, you should be able to set the same option using the command line option `-Sspark.cores.max=xxx` or `--spark-configuration spark.cores.max=xxx` or using the environment variable `SPARK_CONFIGURATION="spark.cores.max=xxx"`

**Comment by Anne623** [comment]
@rcsenkbeil ,I Will try use command line, otherwise, If I use spark kernel with Ipython3, Dose any way to set cores or memory for each notebook? 

Now If I set command line ```SPARK_CONFIGURATION="spark.cores.max=xxx" ``` in Ipython3 kernel.json,  I guess each notebook's cores/resources is the same, But Each notebook is diff job that need diff cores/resources.

So is there has way to set cores/memory for each notebook?

**Comment by rcsenkbeil** [comment]
My recommendation would be to create a separate kernel configuration per notebook. Each configuration can then use a different number of cores and you can simply pick the kernel configuration from IPython 3.0 that suites your needs.

E.g.
```
{
    "display_name": "Spark 1.1.0 (Scala 2.10.4) - 2 cores",
    "language": "scala",
    "argv": [
        "<absolute>/<path>/<to>/local/bin/sparkkernel",
        "--profile",
        "{connection_file}"
     ],
     "env": {
         "SPARK_CONFIGURATION": "spark.cores.max=2"
     },
     "codemirror_mode": "scala"
}
```

**Comment by Anne623** [comment]
I use spark-kernel with spark cluster with option ```-Sspark.cores.max=xxx``` or ```--spark-configuration spark.cores.max=xxx``` it's working,while  using the environment variable ```SPARK_CONFIGURATION="spark.cores.max=xxx"```, it's not working.

otherwise, I use client model below it's working:
```~# /root/local/bin/sparkkernel --master=spark://xx.xxx.xxx.xxx:7077 -Sspark.cores.max=5 -Sspark.executor.memory=5g```
the logs 
```console
15/02/10 15:20:24 [INFO] c.i.s.SparkKernel$$anon$1 - Using spark://xx.xxx.xxx.xxx:7077 as Spark Master
15/02/10 15:20:24 [INFO] c.i.s.SparkKernel$$anon$1 - Using IBM Spark Kernel as Spark application name
15/02/10 15:20:24 [INFO] c.i.s.SparkKernel$$anon$1 - Setting spark.cores.max to 5
15/02/10 15:20:24 [INFO] c.i.s.SparkKernel$$anon$1 - Setting spark.executor.memory to 5g
.....
kernel: com.ibm.spark.kernel.api.Kernel = com.ibm.spark.kernel.api.Kernel@6fa06b3a
15/02/10 15:20:29 [INFO] c.i.s.SparkKernel$$anon$1 - Marking relay as ready for receiving messages
15/02/10 15:20:29 [INFO] c.i.s.k.p.v.r.KernelMessageRelay - Unstashing all messages received!
15/02/10 15:20:29 [INFO] c.i.s.k.p.v.r.KernelMessageRelay - Relay is now fully ready to receive messages!
```

while i use kernel.json in ipython3.0-dev, it can not connet cluster.(In local spark is working fun)
```
{
    "display_name": "Spark",
    "language": "scala",
    "argv": [
      "/root/local/bin/sparkkernel",
       "--master",
       "spark://xx.xxx.xxx.xxx:7077 ",
        "--profile",
        "{connection_file}"
     ],
     "codemirror_mode": "scala"
}
```

The logs:
```console
15/02/10 15:22:43 [INFO] c.i.s.SparkKernel$$anon$1 - Using spark://xx.xxx.xxx.xxx:7077  as Spark Master
15/02/10 15:22:43 [INFO] c.i.s.SparkKernel$$anon$1 - Using IBM Spark Kernel as Spark application name
.....
15/02/10 15:22:44 [WARN] o.a.s.d.c.AppClient$ClientActor - Failed to connect to master
org.apache.spark.SparkException: Invalid master URL: spark://xx.xxx.xxx.xxx:7077 
	
15/02/10 15:22:44 [WARN] o.a.s.s.c.SparkDeploySchedulerBackend - Disconnected from Spark cluster! Waiting for reconnection...
```

Did I some option set wrong in kernel.json?

**Comment by Anne623** [comment]
Sorry, I have a space for --master option ```"spark://xx.xxx.xxx.xxx:7077 ",```, I trim end of the string, it's working. I think spark-kernel need trim for command line options.

**Comment by rcsenkbeil** [comment]
Odd, the environment variable worked for me (I checked before I pasted the kernel.json example). As for the trim, that's a good point. I'll add that as a bug to fix.

**Comment by Anne623** [comment]
Yes, I use 
```
{
    "display_name": "Spark 1.1.0 (Scala 2.10.4) - 2 cores",
    "language": "scala",
    "argv": [
        "<absolute>/<path>/<to>/local/bin/sparkkernel",
        "--profile",
        "{connection_file}"
     ],
     "env": {
         "SPARK_CONFIGURATION": "spark.cores.max=2"
     },
     "codemirror_mode": "scala"
}
```
it's worked, while i want to set one more options llike:```spark.cores.max=2``` and ```spark.executor.memory=5g```, it's not working, I try 
```
{
    "display_name": "Spark",
    "language": "scala",
    "argv": [
      "/root/local/bin/sparkkernel",
        "--profile",
        "{connection_file}"
     ],
    "env": {
         "SPARK_CONFIGURATION": "spark.cores.max=5 spark.executor.memory=5g"
     },
     "codemirror_mode": "scala"
}
```
or 
```
{
    "display_name": "Spark",
    "language": "scala",
    "argv": [
      "/root/local/bin/sparkkernel",
        "--profile",
        "{connection_file}"
     ],
    "env": {
         "SPARK_CONFIGURATION": "spark.cores.max=5",
         "SPARK_CONFIGURATION": "spark.executor.memory=5g"
     },
     "codemirror_mode": "scala"
}

Did I set option use wrong format?

**Comment by rcsenkbeil** [comment]
Ah, sorry. I haven't documented how to use the environment variable option yet. The delimiter for the environment variable is a comma.

So, you would write:
```
{
    "display_name": "Spark",
    "language": "scala",
    "argv": [
      "/root/local/bin/sparkkernel",
        "--profile",
        "{connection_file}"
     ],
    "env": {
         "SPARK_CONFIGURATION": "spark.cores.max=5,spark.executor.memory=5g"
     },
     "codemirror_mode": "scala"
}
```

**Comment by Anne623** [comment]
Thank you, I checked, it's worked.   Anyway, the document is necessary.
