### ISSUE TITLE
Refactor main package from com.ibm.spark to com.ibm.spark.kernel

### ISSUE THREAD

**Issue by chipsenkbeil** [ibm-et/spark-kernel#78]
This is a low priority, but the packaging should ideally be under `com.ibm.spark.kernel` as packages like `com.ibm.spark.boot` and `com.ibm.spark.comm` are specific to the Spark Kernel and not to a generic Spark package.

**Comment by lbustelo** [comment]
I'm closing this one since packages would need to change to `org...`
