### ISSUE TITLE
Update documentation to reflect new Spark configuration options

### ISSUE THREAD

**Issue by chipsenkbeil** [ibm-et/spark-kernel#83]
Our documentation is outdated on the wiki regarding the command line and environment variable options to set the Spark configuration options.

We need to add the following:
- Using `-S<option>=<value>` to set a Spark configuration value
- Using `--spark-configuration <option>=<value>` to set a Spark configuration value
- Using multiple instances of the above command line options will include all in the Spark configuration
- Using `SPARK_CONFIGURATION="<option>=<value>,<option>=<value>,..."` to set Spark configuration values

**Comment by slowenthal** [comment]
was ripping my air out on this.  I did this as an abject hack to get it working with the spark-cassandra connector
exec "$JAVACMD" \
     ${JVM_OPT} \
      \
     -cp "${PROG_HOME}/lib/*${CLASSPATH_SUFFIX}" \
     -Dprog.home="${PROG_HOME}" \
     -Dprog.version="${PROG_VERSION}" \
     -Dspark.cassandra.connection.host=127.0.0.1 \

**Comment by slowenthal** [comment]
Also include examples of how to add additional parameters to kernel.json such as

       "--spark-configuration",
       "spark.cassandra.connection.host=127.0.0.1"

**Comment by lbustelo** [comment]
Based on the work done in #196 

I think that we should deprectate the `--spark-configuration` arg and rather use `SPARK_OPTS` env var that gets sent directly to `spark-submit` or using `SPARK_HOME/conf/spark-defaults.conf`.

**Comment by chipsenkbeil** [comment]
@lbustelo, makes sense to me.

**Comment by lbustelo** [comment]
Closing since we will remove with #219
