### ISSUE TITLE
Multi-Notebook use one sparkContext 

### ISSUE THREAD

**Issue by Anne623** [ibm-et/spark-kernel#87]
Hi All, I use spark-kernel in ipython3, When I new a notebook, spark-kernel will new one sparkContext object for this notebook, How can i  use the same sparkContext object in multiple(diff) notebook?

**Comment by cjm5325** [comment]
Instead of the notebooks each starting their own kernel, you would need to have a kernel already running somewhere and tell IPython to use that kernel instead of starting their own.

**Comment by Anne623** [comment]
Yes, If multiple Notebook use the same kernel, then all variables  in each notebook are global, that's not good. 

 I want use the same spark context object in multiple(diff) notebook because that I started many notebooks, each notebook has its spark context while there no resources for other spark applications. 

so I want to use the same spark context object in notebook that the task in each notebook is serial. So I    want to add  a module sparkContext manager like  [spark-job-rest](https://github.com/Atigeo/spark-job-rest) in spark-kernel, dose it possible?

**Comment by rcsenkbeil** [comment]
It is currently not possible to share the Spark Context across Spark Kernel instances. What that project does is host a Spark Context inside an actor and receive jobs via akka to be run against the internal Spark Context. If that actor fails, then you lose your Spark Context. This is not an ideal solution as it would be better to have stubbed Spark Contexts that can be synced across JVMs to allow a new JVM to pick up where a previous JVM left off if it dies.

**Comment by Anne623** [comment]
Another question is that I have multiple kernel-client to connect the same spark-kernel server, while variables in each client are the same. dose it possible separate variables for each client?

In client A has a variable ```val marked = 3```, In client B also has a variable ```marked = 3```, while In client B change variable marked value, client B will change value too, while I think it's different variable.

**Comment by rcsenkbeil** [comment]
Currently, there is no namespace separation between clients connecting to the kernel. The result is that all clients have the same set of variables, methods, classes, etc. Because of this, you would need to supply your own namespacing in the code that you submit to the kernel.

Something like:

```
object client1_someId {
    val marked = 3
}
```

```
object client2_someId {
    val marked = t
}
```

Using namespace of client 1
```
println(client1.marked)
```

Think of the current implementation of the kernel as giving you a global namespace. Any variables you create are available everywhere. To prevent collisions, you need to wrap your code in some namespace (for now).
