### ISSUE TITLE
ipython 3.0

### ISSUE THREAD

**Issue by virtualirfan** [ibm-et/spark-kernel#91]
With the release of ipython 3, is there still a requirement of checking out a specific changeset of ipython as documented on the getting started page?

```bash
git clone --recursive https://github.com/ipython/ipython.git
cd ipython/
git checkout d3858463c9cd284508ac2deff9a2cde0281d20d3
cd IPython/html/static/components/
git checkout 1968f4f78d7e8cd227d0b3f4cc3183591969b52a
```

**Comment by cjm5325** [comment]
We have to bump to latest to see if anything breaks but after that, barring any time for fixes if necessary, we can get stop pegging ourselves to certain commits.

**Comment by cjm5325** [comment]
Also they bumped the zmq version which doesn't jive with the Akka ZeroMQ module so more investigation needs to be done there.

**Comment by virtualirfan** [comment]
fwiw, on Ubuntu, with ipython 3, I can get spark-kernel to come up and communicate with ipython/jupyterhub if I install the libzmq-dev pkg. Unfortunately, that package interferes with the R kernel. So far, I've found that if I setup the R kernel first, it compiles against the libzmq3 library and continues to work fine after that. If I then install the libzmq-dev deb package, spark-kernel works fine. So, that's the formula I'm using to get around the limitations you guys are facing.

**Comment by wellecks** [comment]
We updated the Vagrant and the docs to support the IPython 3.0.0 release on PR #96

**Comment by rcsenkbeil** [comment]
@wellecks, don't we still have the issue that pyzmq on IPython 3.0 was updated and conflicts with our requirement? Setting up the IPython 3.0 notebook and Spark Kernel on the same machine (not separated using Docker or other VMs) should still have an issue, right?

**Comment by wellecks** [comment]
We successfully upgraded to 3.0 on a few machines and haven't seen the issues; the docs have been updated to include IPython 3.0.0. Given that PR #96 was merged into master I think we can close this one out.
